Repository Franccisco/code-jam-6, pull requests merged in 2020-01, with the labels that each got.

#5 Most of enigma configs
  amphibian-alchemists/.gitignore
  amphibian-alchemists/app/classes/game/gamescreen.py
  amphibian-alchemists/app/classes/game/paper.py
  amphibian-alchemists/app/data/sample/gamestate.json
  amphibian-alchemists/app/data/sample/hello.json
  amphibian-alchemists/app/main.py
Labels: Backend logic

#4 Add machine's keyboard
  amphibian-alchemists/app/classes/game/gamescreen.py
  amphibian-alchemists/app/kvs/game/enigmakeyboard.kv
  amphibian-alchemists/app/kvs/game/gamescreen.kv
  amphibian-alchemists/app/misc/A.png
  amphibian-alchemists/app/misc/B.png
  amphibian-alchemists/app/misc/C.png
  amphibian-alchemists/app/misc/D.png
  amphibian-alchemists/app/misc/E.png
  amphibian-alchemists/app/misc/F.png
  amphibian-alchemists/app/misc/G.png
  amphibian-alchemists/app/misc/H.png
  amphibian-alchemists/app/misc/I.png
  amphibian-alchemists/app/misc/J.png
  amphibian-alchemists/app/misc/K.png
  amphibian-alchemists/app/misc/L.png
  amphibian-alchemists/app/misc/M.png
  amphibian-alchemists/app/misc/N.png
  amphibian-alchemists/app/misc/O.png
  amphibian-alchemists/app/misc/P.png
  amphibian-alchemists/app/misc/Q.png
  amphibian-alchemists/app/misc/R.png
  amphibian-alchemists/app/misc/S.png
  amphibian-alchemists/app/misc/T.png
  amphibian-alchemists/app/misc/U.png
  amphibian-alchemists/app/misc/V.png
  amphibian-alchemists/app/misc/W.png
  amphibian-alchemists/app/misc/X.png
  amphibian-alchemists/app/misc/Y.png
  amphibian-alchemists/app/misc/Z.png
  amphibian-alchemists/app/misc/keydown.png
Labels: Frontend

#16 Rotors
  amphibian-alchemists/app/ancienttech.kv
  amphibian-alchemists/app/classes/game/rotor.py
  amphibian-alchemists/app/kvs/game/gamescreen.kv
  amphibian-alchemists/app/kvs/game/rotor.kv
  amphibian-alchemists/app/misc/gear.png
  amphibian-alchemists/app/misc/rotor.png
Labels: Frontend

#15 Change game title
  amphibian-alchemists/app/kvs/mainscreen.kv
  amphibian-alchemists/app/main.py
Labels: enhancement
